// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWUPGQ3BLdqVnTKkI7g1k9ra9NXx34DzM',
    appId: '1:346016803416:web:50076107fe5f11f644f82d',
    messagingSenderId: '346016803416',
    projectId: 'app-cic-139dd',
    authDomain: 'app-cic-139dd.firebaseapp.com',
    storageBucket: 'app-cic-139dd.firebasestorage.app',
    measurementId: 'G-BN3QR078NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoGaPgny-GhD6h3ObVXL7Q2oTMvhc5nhI',
    appId: '1:346016803416:android:fe3d06ccc91eced144f82d',
    messagingSenderId: '346016803416',
    projectId: 'app-cic-139dd',
    storageBucket: 'app-cic-139dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxf3RjnTSDbveien2mwsOQZ9QbAujoIxA',
    appId: '1:346016803416:ios:7d9e9ae9c7de55f644f82d',
    messagingSenderId: '346016803416',
    projectId: 'app-cic-139dd',
    storageBucket: 'app-cic-139dd.firebasestorage.app',
    iosBundleId: 'com.example.appCic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWUPGQ3BLdqVnTKkI7g1k9ra9NXx34DzM',
    appId: '1:346016803416:web:574840567970188044f82d',
    messagingSenderId: '346016803416',
    projectId: 'app-cic-139dd',
    authDomain: 'app-cic-139dd.firebaseapp.com',
    storageBucket: 'app-cic-139dd.firebasestorage.app',
    measurementId: 'G-3996M2YZ4Q',
  );
}
